FROM python:3.11
WORKDIR /backend

COPY backend/requirements.txt backend/.env backend/api.py backend/.flaskenv ./
COPY ./backend/models ./models
COPY ./backend/services ./services
COPY ./backend/utils ./utils
RUN pip install -r ./requirements.txt
ENV FLASK_ENV development

EXPOSE 5000
EXPOSE 3306
ENTRYPOINT [ "python" ]

CMD [ "api.py" ]