FROM python:3.11
WORKDIR /devops-back

COPY ./devops-back/requirements.txt ./devops-back/.env ./devops-back/api.py ./devops-back/.flaskenv ./
COPY ./devops-back/models ./models
COPY ./devops-back/services ./services
COPY ./devops-back/utils ./utils
RUN pip install -r ./requirements.txt
ENV FLASK_ENV development

EXPOSE 5000
EXPOSE 3306
ENTRYPOINT [ "python" ]

CMD [ "api.py" ]